CREATE TABLE USERS(
USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
EMAIL VARCHAR2(256) NOT NULL,
FULLNAME VARCHAR2(256) NOT NULL,
PASSWORD VARCHAR(256) NOT NULL);

CREATE TABLE TWEETS(
TWEET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
USER_ID INTEGER NOT NULL,
MESSAGE VARCHAR2(256) NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID));
